app:
  http_server:
    host: "0.0.0.0"
    port: 8080
    api_host: "localhost:8080"
    metric_port: 8081
  graceful_timeout: "5s"

sage:
  level: "info"
  app_id: 1
  deployment_environment: test
  system: bodyfuel
  stand_type: test
  pod_name: bodyfuel-0

postgres:
  host: "localhost"
  port: 5432
  database: "backend_db"
  user: "drobysheva.daria"
  password: "backend_pass"

minio:
  endpoint: "http://localhost:9000"
  access_key: "minioadmin"
  secret_key: "minioadmin"
  bucket: "avatars"
  region: "us-east-1"
  public_url: "http://localhost:9000/avatars"
  presign_ttl: "5m"
